frontend: null

preencoder: linear
preencoder_conf:
    input_size: 1024
    output_size: 80

encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 8
    linear_units: 2048
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d2
    # 20 ms resolution (1/2 length)
    normalize_before: true
    interctc_layer_idx: [11]  # use penultimate layer; 1-indexed
    interctc_use_conditioning: false  # self-conditioning

decoder: null

model_conf:
    ctc_weight: 1.0
    lsm_weight: 0.1
    length_normalized_loss: false
    extract_feats_in_collect_stats: false
    interctc_weight: 0.25
    # use penultimate layer
    aux_ctc:
        '10':
            - syl
            - son
            - cons
            - cont
            - delrel
            - lat
            - nas
            - strid
            - voi
            - sg
            - cg
            - ant
            - cor
            - distr
            - lab
            - hi
            - lo
            - back
            - round
            - velaric
            - tense
            - long


aux_ctc_tasks: ["syl", "son", "cons", "cont", "delrel", "lat", "nas", "strid", "voi", "sg", "cg", "ant", "cor", "distr", "lab", "hi", "lo", "back", "round", "velaric", "tense", "long"]


seed: 11711
log_interval: 50
num_att_plot: 0
num_workers: 6
batch_type: numel
num_iters_per_epoch: 5000
batch_bins: 7000000
max_epoch: 100
patience: none
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
use_wandb: true

use_amp: true
cudnn_deterministic: false
cudnn_benchmark: false

optim: adam
optim_conf:
    lr: 0.0001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 25000
