frontend: null

preencoder: linear
preencoder_conf:
    input_size: 1024
    output_size: 80

encoder: transformer
encoder_conf:
    output_size: 256
    attention_heads: 4
    linear_units: 1024
    num_blocks: 12
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d2
    normalize_before: true
    interctc_layer_idx: [11]  # use penultimate layer; 1-indexed
    interctc_use_conditioning: false  # self-conditioning

decoder: null

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
    extract_feats_in_collect_stats: false
    interctc_weight: 0.25
    aux_ctc:
        '10':
            - syl
            - son
            - cons
            - cont
            - delrel
            - lat
            - nas
            - strid
            - voi
            - sg
            - cg
            - ant
            - cor
            - distr
            - lab
            - hi
            - lo
            - back
            - round
            - velaric
            - tense
            - long


aux_ctc_tasks: ["syl", "son", "cons", "cont", "delrel", "lat", "nas", "strid", "voi", "sg", "cg", "ant", "cor", "distr", "lab", "hi", "lo", "back", "round", "velaric", "tense", "long"]


seed: 2022
log_interval: 400
num_att_plot: 0
num_workers: 4
sort_in_batch: descending
sort_batch: descending
batch_type: numel
batch_bins: 16000000
accum_grad: 4
max_epoch: 70
patience: none
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

use_amp: true
cudnn_deterministic: false
cudnn_benchmark: false

optim: adam
optim_conf:
    lr: 0.001
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000
