seed: 11711
freeze_param: [
"frontend.upstream"
]

frontend: s3prl
frontend_conf:
    frontend_conf:
        upstream: xls_r_300m
    download_dir: ./hub
    multilayer_feature: True

encoder: allophant
encoder_conf:
    input_size: 1024
    phoneme_embedding_size: 640,
    composition_features:
      - stress
      - syllabic
      - short
      - long
      - consonantal
      - sonorant
      - continuant
      - delayedRelease
      - approximant
      - tap
      - trill
      - nasal
      - lateral
      - labial
      - round
      - labiodental
      - coronal
      - anterior
      - distributed
      - strident
      - dorsal
      - high
      - low
      - front
      - back
      - tense
      - retractedTongueRoot
      - advancedTongueRoot
      - periodicGlottalSource
      - epilaryngealSource
      - spreadGlottis
      - constrictedGlottis
      - fortis
      - raisedLarynxEjective
      - loweredLarynxImplosive
      - click
    allophone_languages:
      - pl
      - de
    # phoible_path:
    # blank_offset:
    # use_allophone_layer: false

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false

log_interval: 400
num_att_plot: 0
num_workers: 4
sort_in_batch: descending
sort_batch: descending
batch_type: numel
batch_bins: 16000000
accum_grad: 4
max_epoch: 70
patience: none
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10

use_amp: true
cudnn_deterministic: false
cudnn_benchmark: false

optim: adam
optim_conf:
    lr: 0.002
    weight_decay: 0.000001
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 15000
