# https://github.com/espnet/espnet/blob/master/egs2/owsm_v3.1/s2t1/conf/train_s2t_ebf_conv2d_size1024_e18_d18_piecewise_lr2e-4_warmup60k_flashattn.yaml

preprocessor: s2t
preprocessor_conf:
    text_prev_name: text.prev
    text_ctc_name: text.ctc
    fs: 16000
    na_symbol: "<na>"
    speech_length: 20
    speech_resolution: 0.02
    speech_init_silence: 20
    text_prev_apply_prob: 0.5 # whether to condition on text_prev
        # if text_prev is <na>, applying text_prev doesn't do anything
        #   thus for ASR and phoneme recognition, this doesn't do anything
        #   but for G2P and P2G, what removing the context does is to
        #   rely only on the audio
        # TODO: fully removing the context might be too harsh though?
        #   may want to try masking
    time_apply_prob: 0.0  # we don't have timestamps
    notime_symbol: "<notimestamps>"
    first_time_symbol: "<0.00>"
    last_time_symbol: "<20.00>"

frontend_conf:
    n_fft: 512
    win_length: 400
    hop_length: 160

specaug: specaug
specaug_conf:
    apply_time_warp: false
    time_warp_window: 5
    time_warp_mode: bicubic
    apply_freq_mask: true
    freq_mask_width_range:
    - 0
    - 27
    num_freq_mask: 2
    apply_time_mask: true
    time_mask_width_ratio_range:
    - 0.
    - 0.05
    num_time_mask: 10

encoder: e_branchformer
encoder_conf:
    output_size: 1024
    attention_heads: 16
    attention_layer_type: selfattn
    pos_enc_layer_type: abs_pos
    rel_pos_type: latest
    qk_norm: false    # qk norm
    use_flash_attn: false    # flash attn - Delta only
    cgmlp_linear_units: 4096
    cgmlp_conv_kernel: 31
    use_linear_after_conv: false
    gate_activation: identity
    num_blocks: 18
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    attention_dropout_rate: 0.1
    input_layer: conv2d
    layer_drop_rate: 0.0
    linear_units: 4096
    positionwise_layer_type: linear
    use_ffn: true
    macaron_ffn: true
    merge_conv_kernel: 31

decoder: transformer
decoder_conf:
    attention_heads: 16
    linear_units: 4096
    num_blocks: 18
    dropout_rate: 0.1
    positional_dropout_rate: 0.1
    self_attention_dropout_rate: 0.1
    src_attention_dropout_rate: 0.1

model_conf:
    ctc_weight: 0.3
    lsm_weight: 0.1
    length_normalized_loss: false
    sym_na: "<na>"

optim: adamw
optim_conf:
    lr: 2.0e-04
    betas:
    - 0.9
    - 0.98
    eps: 1.0e-06
    weight_decay: 0.0
scheduler: piecewiselinearwarmuplr
scheduler_conf:
    warmup_steps_list: [0, 30000, 60000]
    warmup_lr_list: [0., 5.0e-05, 2.0e-04]

# 4 GPU/node x 16 nodes = 64
batch_type: unsorted
batch_size: 256
accum_grad: 1
num_iters_per_epoch: 15000
max_epoch: 45
patience: none
init: none
best_model_criterion:
-   - valid
    - acc
    - max
-   - valid
    - total_count
    - max
keep_nbest_models: 5
nbest_averaging_interval: 5     # average ckpt every 5 epochs
use_amp: true
num_workers: 4
unused_parameters: false
seed: 42
num_att_plot: 0     # set to 0 due to flash_attn
sharded_ddp: false
