seed: 11711
freeze_param: [
  "frontend.encoder.feature_extractor"
]

frontend: huggingface
frontend_conf:
    model: "facebook/wav2vec2-xls-r-300m"
    download_dir: ./hub

normalize: null

encoder: allophant
encoder_conf:
    phoneme_embedding_size: 640
    # Blank offset 2 to handle <unk> token from Stage 5
    blank_offset: 2
    # <sos/eos> token from Stage 5
    additional_special_tokens: 1
    feature_type: panphon
    use_allophone_layer: false
    phoneme_inventory_file: data/token_list/word/tokens.txt
    composition_inventories_file: dump/raw/inventories.json
    composition_features:
      - syl
      - son
      - cons
      - cont
      - delrel
      - lat
      - nas
      - strid
      - voi
      - sg
      - cg
      - ant
      - cor
      - distr
      - lab
      - hi
      - lo
      - back
      - round
      - velaric
      - tense
      # - long
    language_id_mapping_path: dump/raw/supported_languages.json
    utt_id_separator: "_"

model_conf:
    frontend_gradients: true
    extract_feats_in_collect_stats: false
    ctc_weight: 1.0
    interctc_weight: 0.5
    lsm_weight: 0.1
    length_normalized_loss: false
    aux_ctc_share_vocab: "dump/raw/train/feature_values.json"
    aux_ctc:
      '0':
          - syl
          - son
          - cons
          - cont
          - delrel
          - lat
          - nas
          - strid
          - voi
          - sg
          - cg
          - ant
          - cor
          - distr
          - lab
          - hi
          - lo
          - back
          - round
          - velaric
          - tense
          # - long

aux_ctc_tasks: ["syl", "son", "cons", "cont", "delrel", "lat", "nas", "strid", "voi", "sg", "cg", "ant", "cor", "distr", "lab", "hi", "lo", "back", "round", "velaric", "tense"] # , "long"]

log_interval: 1
num_att_plot: 0
num_workers: 32
sort_in_batch: descending
sort_batch: descending
batch_type: numel
batch_bins: 2500000
accum_grad: 4
max_epoch: 45
patience: none
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
-   - valid
    - total_count
    - max
keep_nbest_models: 10
unused_parameters: true
log_level: INFO

use_amp: true
cudnn_deterministic: false
cudnn_benchmark: false

optim: adamw
optim_conf:
    lr: 0.0003
    weight_decay: 0.000001
    betas:
    - 0.9
    - 0.98
    eps: 1.0e-06
scheduler: warmuplr
scheduler_conf:
    warmup_steps: 2500  # 625

ctc_conf:
    zero_infinity: true
    elementwise_affine: false
